2025-03-01 16:38:33,731 ERROR: 数据收集出错: (sqlite3.OperationalError) database is locked
[SQL: INSERT INTO alert (device_id, timestamp, alert_type, message, severity, resolved, resolved_time, resolved_by, resolution_notes) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?) RETURNING id]
[parameters: (1, 1740818184.177841, 'high_latency', '设备 核心交换机 (192.168.1.1) 延迟过高: 191.5ms > 100ms', 'warning', 0, None, None, None)]
(Background on this error at: https://sqlalche.me/e/20/e3q8) [in C:\Users\28637\Desktop\demo1\实例3\app.py:352]
